name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      #       checkout
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      #       build project and run all tests & checks
      - name: Build with Maven
        run: mvn -B package -file pom.xml

      #       Upload code coverage report to Codecov